import React from 'react';
import { Link } from 'react-router-dom';
import './Terms.css';

function Terms() {
  return (
    <div className="terms-page">
      <nav className="terms-nav">
        <div className="container">
          <Link to="/" className="logo-link">
            <span className="logo-icon">📊</span>
            <span className="logo-text">Watnew</span>
          </Link>
          <Link to="/" className="btn-nav">Back to Home</Link>
        </div>
      </nav>

      <div className="container">
        <div className="terms-content">
          <h1>Terms of Service</h1>
          <p className="last-updated">Last updated: January 2026</p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Watnew ("the Service"), you accept and agree to be bound by the terms 
              and provision of this agreement. If you do not agree to abide by the above, please do not use 
              this service.
            </p>
          </section>

          <section>
            <h2>2. Subscription Service</h2>
            <p>
              Watnew is a subscription-based service priced at $99 per month. By subscribing, you agree to:
            </p>
            <ul>
              <li>Pay the monthly subscription fee in advance</li>
              <li>Automatic renewal of your subscription each month</li>
              <li>Access to the Service is granted only to active, paying subscribers</li>
            </ul>
          </section>

          <section>
            <h2>3. Cancellation and Refunds</h2>
            <p>
              You may cancel your subscription at any time through your billing dashboard. Cancellation will 
              take effect at the end of your current billing period. You will retain access to the Service 
              until the end of the period you have paid for.
            </p>
            <p>
              We offer a 7-day money-back guarantee for new subscribers. If you are not satisfied with the 
              Service within 7 days of your first payment, contact us for a full refund.
            </p>
          </section>

          <section>
            <h2>4. Use of Service</h2>
            <p>
              You agree to use Watnew only for lawful purposes and in accordance with these Terms. You agree 
              not to:
            </p>
            <ul>
              <li>Use the Service in any way that violates any applicable law or regulation</li>
              <li>Attempt to gain unauthorized access to the Service or related systems</li>
              <li>Interfere with or disrupt the Service or servers</li>
              <li>Use the Service to create models for illegal or fraudulent purposes</li>
            </ul>
          </section>

          <section>
            <h2>5. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are owned by Watnew and are 
              protected by international copyright, trademark, and other intellectual property laws.
            </p>
            <p>
              You retain ownership of any financial models and data you create using the Service. However, 
              you grant Watnew a license to use aggregated, anonymized data for service improvement purposes.
            </p>
          </section>

          <section>
            <h2>6. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, either express 
              or implied. Watnew does not guarantee the accuracy, completeness, or usefulness of any financial 
              projections generated by the Service. Financial models are for planning purposes only and should 
              not be considered as financial advice.
            </p>
          </section>

          <section>
            <h2>7. Limitation of Liability</h2>
            <p>
              In no event shall Watnew be liable for any indirect, incidental, special, consequential, or 
              punitive damages, including without limitation, loss of profits, data, use, goodwill, or other 
              intangible losses, resulting from your use of the Service.
            </p>
          </section>

          <section>
            <h2>8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material 
              changes via email or through the Service. Your continued use of the Service after such 
              modifications constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2>9. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the United States 
              and the state in which Watnew operates, without regard to its conflict of law provisions. Any 
              disputes arising from these Terms or your use of the Service shall be resolved in the courts of 
              that jurisdiction.
            </p>
          </section>

          <section>
            <h2>10. Severability</h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions 
              will continue in full force and effect.
            </p>
          </section>

          <section>
            <h2>11. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              <strong>Email:</strong> <a href="mailto:help@watnew.me">help@watnew.me</a><br />
              <strong>Website:</strong> <Link to="/">watnew.me</Link>
            </p>
          </section>
        </div>
      </div>

      <footer className="terms-footer">
        <div className="container">
          <div style={{ marginBottom: '15px' }}>
            <Link to="/" style={{ marginRight: '20px' }}>← Back to Home</Link>
            <a href="mailto:help@watnew.me" style={{ color: '#78c0e0', textDecoration: 'none' }}>help@watnew.me</a>
          </div>
          <p>&copy; 2026 Watnew</p>
        </div>
      </footer>
    </div>
  );
}

export default Terms;